=== jxtxinbing/opssrc_org/ops/schema/ops.metaschema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://git.openswich.net/schema/ops-db-metaschema#",
  "description": "OpenSwitch Database metaschema",
  "definitions": {

    "atomicDataType": {
      "type": "string",
      "enum": [
        "integer",
        "real",
        "boolean",
        "string",
        "uuid"
      ]
    },

    "categoryValues": {
      "type": "string",
      "enum": [
        "configuration",
        "status",
        "statistics"
      ]
    },

    "relationshipValues": {
      "type": "string",
      "enum": [
        "reference",
        "1:m",
        "m:1"
      ]
    },

    "refTypeValues": {
      "type": "string",
      "enum": [
        "strong",
        "weak",
        "weak_gc"
      ]
    },

    "documentation": {
      "type": "array",
      "items": {
          "type": "string"
      },
      "uniqueItems": false
    },

    "atomicType": {
      "oneOf": [
        {
          "$ref": "#/definitions/atomicDataType"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "$ref": "#/definitions/atomicDataType"
            }
          },
          "required": [
            "type"
          ],
          "additionalProperties": false
        }
      ]
    },

    "integerType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^integer$"},
        "enum": {
          "type": "array",
          "items": {"type": "integer"},
          "minItems": 1,
          "uniqueItems": true
        },
        "minInteger": {"type": "integer"},
        "maxInteger": {"type": "integer"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "realType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^real$"},
        "enum": {
          "type": "array",
          "items": {"type": "number"},
          "minItems": 1,
          "uniqueItems": true
        },
        "minReal": {"type": "number"},
        "maxReal": {"type": "number"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "stringType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^string$"},
        "enum": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"},
        "minLength": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"},
        "maxLength": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "uuidType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^uuid$"},
        "enum": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"},
        "refTable": {"type": "string", "pattern": "^[_a-zA-Z][_a-zA-Z0-9]*$"},
        "refType": {"$ref": "#/definitions/refTypeValues"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "baseType":{
      "anyOf": [
        {"$ref":"#/definitions/atomicType"},
        {"$ref":"#/definitions/integerType"},
        {"$ref":"#/definitions/realType"},
        {"$ref":"#/definitions/stringType"},
        {"$ref":"#/definitions/uuidType"}
      ]
    },

    "valueMap": {
      "type": "object",
      "properties": {
        "type": {"$ref": "#/definitions/baseType"},
        "doc": {"$ref": "#/definitions/documentation"},
        "group": {"$ref": "#/definitions/groupPath"},
        "emptyValue": {"type": ["number","string","boolean"]}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "valueMapField": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "$ref": "#/definitions/valueMap"
        }
      },
      "additionalProperties": false
    },

    "valueMapType":{
      "type": "object",
      "properties":{
        "omitCodeGeneration": {"type":"boolean","default": false},
        "valueType": {"$ref": "#/definitions/baseType"},
        "valueMap": {"$ref": "#/definitions/valueMapField"},
        "min": {"$ref": "#/definitions/integerLimit"},
        "max": {"$ref": "#/definitions/integerLimit"}
      },
      "required": ["valueMap","valueType"],
      "additionalProperties": false
    },

    "integerLimit": {
      "anyOf": [
        {"$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"},
        {"type": "string", "pattern": "^unlimited$"}
      ]
    },

    "path": {
      "type": "string"
    },

    "pathArray": {
      "type": "array",
      "items": {"$ref": "#/definitions/path"}
    },

    "indexArray": {
      "type": "array",
      "items": {
        "$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"
      }
    },

    "groupPath": {
      "anyOf": [
        {"$ref": "#/definitions/path"},
        {"$ref": "#/definitions/pathArray"}
      ]
    },

    "perValue": {
       "type": "object",
       "properties":{
         "value": {},
         "category": {"type": "string"}
       },
       "required": ["value", "category"],
       "additionalProperties": false
    },

    "perValueArray": {
      "type": "array",
      "items": {"$ref": "#/definitions/perValue"}
    },

    "categoryType":{
       "oneOf": [
         {"$ref": "#/definitions/categoryValues"},
         {
           "type": "object",
           "properties": {
             "follows": {"type": "string"}
           },
           "required": ["follows"],
           "additionalProperties": false
         },
         {
           "type": "object",
           "properties": {
             "per-value": {"$ref": "#/definitions/perValueArray"}
           },
           "required": ["per-value"],
           "additionalProperties": false
         }
       ]
    },

    "mapType": {
      "type": "object",
      "properties":{
        "key": {"$ref": "#/definitions/baseType"},
        "value": {"$ref": "#/definitions/baseType"},
        "min": {"$ref": "#/definitions/integerLimit"},
        "max": {"$ref": "#/definitions/integerLimit"}
      },
      "required": ["key"],
      "additionalProperties": false
    },

    "columnType": {
      "oneOf": [
        { "$ref": "#/definitions/atomicType" },
        { "$ref": "#/definitions/mapType" },
        { "$ref": "#/definitions/valueMapType" }
      ]
    },

    "column": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/columnType"
        },
        "ephemeral": {
          "type": "boolean",
          "default": false
        },
        "mutable": {
          "type": "boolean",
          "default": true
        },
        "category": {
          "$ref": "#/definitions/categoryType"
        },
        "group": {
          "$ref": "#/definitions/groupPath"
        },
        "title": {
          "type": "string"
        },
        "doc": {
          "$ref": "#/definitions/documentation"
        },
        "relationship": {
          "$ref": "#/definitions/relationshipValues"
        },
        "emptyValue": {
          "type": ["number","string","boolean"]
        },
        "keyname": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ],
      "additionalProperties": false
    },

    "columns": {
      "type": "object",
      "patternProperties": {
        "^[_a-zA-Z][_a-zA-Z0-9]*$": {
          "$ref": "#/definitions/column"
        }
      },
      "additionalProperties": false
    },

    "groupDoc": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "$ref": "#/definitions/documentation"
        }
      },
      "additionalProperties": false
    },

    "table": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "doc": {
          "$ref": "#/definitions/documentation"
        },
        "columns": {
          "$ref": "#/definitions/columns"
        },
        "isRoot": {
          "type": "boolean",
          "default": false
        },
        "maxRows": {
          "type": "integer",
          "minimum": 1
        },
        "indexes": {
          "$ref": "#/definitions/indexArray"
        },
        "group": {
          "$ref": "#/definitions/groupPath"
        },
        "groupDoc": {
          "$ref": "#/definitions/groupDoc"
        }

      },
      "required": [
        "columns"
      ],
      "additionalProperties": false
    },

    "tableRef": {
      "type": "object",
      "properties": {
        "$ref": {
          "type": "string"
        }
      },
      "required": [
        "$ref"
      ]
    },

    "tables": {
      "type": "object",
      "patternProperties": {
         "^[_a-zA-Z][_a-zA-Z0-9]*$": {
          "$ref": "#/definitions/table"
        }
      },
      "additionalProperties": false
    }

  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "id": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "cksum": {
      "type": "string",
      "pattern": "[0-9]{12} [0-9]{7}"
    },
    "doc": {
      "$ref": "#/definitions/documentation"
    },
    "groups": {
      "$ref": "#/definitions/groups"
    },
    "tables": {
      "$ref": "#/definitions/tables"
    }
  },
  "required": [
    "name",
    "version",
    "tables"
  ],
  "additionalProperties": false
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/prefix_list.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/prefix_list.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "Prefix_List": {
      "columns": {
        "name": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 80
            }
          },
          "doc": [
            "Name of the prefix list."
          ],
          "group": "/Global IP Address Prefix List Configuration"
        },
        "description": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 80
            },
            "min": 0,
            "max": 1
          },
          "group": "/Global IP Address Prefix List Configuration"
        },
        "prefix_list_entries": {
          "category": "configuration",
          "relationship": "1:m",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 4294967295
            },
            "value": {
              "type": "uuid",
              "refTable": "Prefix_List_Entry"
            },
            "min": 0,
            "max": "unlimited"
          },
          "keyname": "preference",
          "doc": [
            "Prefix list entries keyed by preference value."
          ],
          "group": "/Global IP Address Prefix List Configuration"
        },
        "other_config": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          },
          "group": "/Common Columns"
        },
        "external_ids": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          },
          "group": "/Common Columns"
        }
      },
      "indexes": [
        [
          "name"
        ]
      ],
      "isRoot": true,
      "title": "Prefix List",
      "groupDoc": {
        "/Common Columns": [
          "The overall purpose of these columns is described under `Common Columns` at the",
          "beginning of this document."
        ]
      }
    }
  }
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/cli_alias.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/cli_alias.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "CLI_Alias": {
      "columns": {
        "alias_name": {
          "category": "configuration",
          "type": "string",
          "doc": [
            "Shortcut name configured by the user for a set of commands."
          ]
        },
        "alias_definition": {
          "category": "configuration",
          "type": "string",
          "doc": [
            "The list of commands to be executed when the shortcut is used. Different",
            "commands can be separated by \";\". Runtime arguments can be specified using $1,",
            "$2 etc. Any extra arguments, will be added at the end of last command. Eg:",
            "Execute the command \"alias mycmd hostname $1; console length $2; console width",
            "$3\" to configure \"mycmd\" as shortcut. On executing \"mycmd Switch1 80 24\", it",
            "will be expanded to \"hostname Switch1; console length 80; console width 24\".",
            "\"mycmd\" will be stored in alias_name\" and \"hostname $1; console length $2;",
            "console width $3\" will be saved in alias_definition."
          ]
        },
        "other_config": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          }
        },
        "external_ids": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          },
          "group": "/Common Columns"
        }
      },
      "indexes": [
        [
          "alias_name"
        ]
      ],
      "isRoot": true,
      "doc": [
        "Alias configurations for the command line interface."
      ],
      "groupDoc": {
        "/Common Columns": [
          "The overall purpose of these columns is described under `Common Columns` at the",
          "beginning of this document."
        ]
      }
    }
  }
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/mstp_instance.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/mstp_instance.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "MSTP_Instance": {
      "columns": {
        "vlans": {
          "category": "configuration",
          "relationship": "reference",
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "VLAN",
              "refType": "weak"
            },
            "min": 0,
            "max": 4094
          },
          "doc": [
            "VLANs included in the MSTP instance."
          ],
          "group": "/Configurations"
        },
        "priority": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 61440
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Set this value to specify the priority value, configured as a multiple of 4096",
            "The lower a priority value, the higher the priority. Default value is 8."
          ],
          "group": "/Configurations",
          "emptyValue": 8
        },
        "bridge_identifier": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 45
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "+ The root bridge ID for CIST. Default value 64 bit string(4 bit priority",
            "+ 12 bit Instance ID",
            "+ 48bit system MAC address)"
          ],
          "group": "/Configurations"
        },
        "hardware_grp_id": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "The hardware spanning tree group ID. Default value is 0."
          ],
          "group": "/Status",
          "emptyValue": 0
        },
        "designated_root": {
          "category": "status",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 45
            }
          },
          "doc": [
            "The root bridge name for a MSTP instance."
          ],
          "group": "/Status"
        },
        "root_path_cost": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 200000000
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "The path cost from the transmitting Bridge to the Root Bridge for the MSTI."
          ],
          "group": "/Status"
        },
        "root_priority": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 61440
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "The root bridge priority. The lower a priority value, the higher the priority.",
            "Default value is 32768."
          ],
          "group": "/Status",
          "emptyValue": 32768
        },
        "remaining_hops": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 40
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Once known, contains the hop count after which the MSTP BPDU of this instance",
            "are discarded."
          ],
          "group": "/Status"
        },
        "root_port": {
          "category": "status",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 45
            }
          },
          "doc": [
            "Specifies the root port name for a MSTP instance."
          ],
          "group": "/Status"
        },
        "time_since_top_change": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "The time last topology change happened for this instance. The format for this is",
            "number of seconds from epoch."
          ],
          "group": "/Status"
        },
        "topology_change_count": {
          "category": "statistics",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 2147483647
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "The total number of topology changes that have occurred for this instance."
          ],
          "group": "/Status"
        },
        "topology_unstable": {
          "category": "status",
          "type": {
            "key": {
              "type": "boolean"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "This is set to `true` when a topology change has occurred. Once topology",
            "stabilizes it will be set back to `false`. Default is `false`."
          ],
          "group": "/Status",
          "emptyValue": false
        },
        "mstp_instance_ports": {
          "category": "configuration",
          "relationship": "1:m",
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "MSTP_Instance_Port"
            },
            "min": 0,
            "max": "unlimited"
          },
          "doc": [
            "MSTP configuration for port."
          ],
          "group": "/Configurations"
        }
      },
      "title": "MSTP instance info",
      "doc": [
        "This represents information regarding a Bridge's Bridge Protocol entity for the",
        "specified Spanning Tree instance."
      ],
      "groupDoc": {
        "/Status": [
          "These are status parameters for a particular MSTP instance. These values will be",
          "calculated at the time of protocol initialization."
        ]
      }
    }
  }
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/bgp_community_filter.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/bgp_community_filter.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "BGP_Community_Filter": {
      "columns": {
        "name": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 80
            }
          },
          "doc": [
            "Name of the list."
          ],
          "group": "/Global Community and Extended Community Configuration"
        },
        "permit": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 80
            },
            "min": 0,
            "max": "unlimited"
          },
          "doc": [
            "Permitted POSIX regular expressions."
          ],
          "group": "/Global Community and Extended Community Configuration"
        },
        "deny": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 80
            },
            "min": 0,
            "max": "unlimited"
          },
          "doc": [
            "Denied POSIX regular expressions."
          ],
          "group": "/Global Community and Extended Community Configuration"
        },
        "type": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "extcommunity-list",
                "community-list"
              ]
            }
          },
          "doc": [
            "There are two types, either \"extcommunity-list\" or \"community-list\"."
          ],
          "group": "/Global Community and Extended Community Configuration"
        }
      },
      "indexes": [
        [
          "name"
        ]
      ],
      "isRoot": true,
      "title": "BGP Community Filter"
    }
  }
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/notification_subscriber.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/notification_subscriber.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "Notification_Subscriber": {
      "columns": {
        "name": {
          "category": "configuration",
          "type": "string",
          "mutable": false,
          "doc": [
            "Name of the notification subscriber."
          ],
          "group": "/Configuration"
        },
        "type": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "ws"
              ]
            }
          },
          "mutable": false,
          "doc": [
            "Notification transport type. For WebSockets the type is \"ws\"."
          ],
          "group": "/Configuration"
        },
        "notification_subscriptions": {
          "category": "configuration",
          "relationship": "1:m",
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "uuid",
              "refTable": "Notification_Subscription"
            },
            "min": 0,
            "max": "unlimited"
          },
          "keyname": "name",
          "doc": [
            "List of notification subscriptions by name for this subscriber."
          ],
          "group": "/Configuration"
        }
      },
      "indexes": [
        [
          "name"
        ]
      ],
      "isRoot": true,
      "title": "Notification subscriber information"
    }
  }
}
