=== jxtxinbing/opssrc_org/ops/schema/ops.metaschema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://git.openswich.net/schema/ops-db-metaschema#",
  "description": "OpenSwitch Database metaschema",
  "definitions": {

    "atomicDataType": {
      "type": "string",
      "enum": [
        "integer",
        "real",
        "boolean",
        "string",
        "uuid"
      ]
    },

    "categoryValues": {
      "type": "string",
      "enum": [
        "configuration",
        "status",
        "statistics"
      ]
    },

    "relationshipValues": {
      "type": "string",
      "enum": [
        "reference",
        "1:m",
        "m:1"
      ]
    },

    "refTypeValues": {
      "type": "string",
      "enum": [
        "strong",
        "weak",
        "weak_gc"
      ]
    },

    "documentation": {
      "type": "array",
      "items": {
          "type": "string"
      },
      "uniqueItems": false
    },

    "atomicType": {
      "oneOf": [
        {
          "$ref": "#/definitions/atomicDataType"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "$ref": "#/definitions/atomicDataType"
            }
          },
          "required": [
            "type"
          ],
          "additionalProperties": false
        }
      ]
    },

    "integerType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^integer$"},
        "enum": {
          "type": "array",
          "items": {"type": "integer"},
          "minItems": 1,
          "uniqueItems": true
        },
        "minInteger": {"type": "integer"},
        "maxInteger": {"type": "integer"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "realType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^real$"},
        "enum": {
          "type": "array",
          "items": {"type": "number"},
          "minItems": 1,
          "uniqueItems": true
        },
        "minReal": {"type": "number"},
        "maxReal": {"type": "number"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "stringType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^string$"},
        "enum": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"},
        "minLength": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"},
        "maxLength": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "uuidType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^uuid$"},
        "enum": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"},
        "refTable": {"type": "string", "pattern": "^[_a-zA-Z][_a-zA-Z0-9]*$"},
        "refType": {"$ref": "#/definitions/refTypeValues"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "baseType":{
      "anyOf": [
        {"$ref":"#/definitions/atomicType"},
        {"$ref":"#/definitions/integerType"},
        {"$ref":"#/definitions/realType"},
        {"$ref":"#/definitions/stringType"},
        {"$ref":"#/definitions/uuidType"}
      ]
    },

    "valueMap": {
      "type": "object",
      "properties": {
        "type": {"$ref": "#/definitions/baseType"},
        "doc": {"$ref": "#/definitions/documentation"},
        "group": {"$ref": "#/definitions/groupPath"},
        "emptyValue": {"type": ["number","string","boolean"]}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "valueMapField": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "$ref": "#/definitions/valueMap"
        }
      },
      "additionalProperties": false
    },

    "valueMapType":{
      "type": "object",
      "properties":{
        "omitCodeGeneration": {"type":"boolean","default": false},
        "valueType": {"$ref": "#/definitions/baseType"},
        "valueMap": {"$ref": "#/definitions/valueMapField"},
        "min": {"$ref": "#/definitions/integerLimit"},
        "max": {"$ref": "#/definitions/integerLimit"}
      },
      "required": ["valueMap","valueType"],
      "additionalProperties": false
    },

    "integerLimit": {
      "anyOf": [
        {"$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"},
        {"type": "string", "pattern": "^unlimited$"}
      ]
    },

    "path": {
      "type": "string"
    },

    "pathArray": {
      "type": "array",
      "items": {"$ref": "#/definitions/path"}
    },

    "indexArray": {
      "type": "array",
      "items": {
        "$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"
      }
    },

    "groupPath": {
      "anyOf": [
        {"$ref": "#/definitions/path"},
        {"$ref": "#/definitions/pathArray"}
      ]
    },

    "perValue": {
       "type": "object",
       "properties":{
         "value": {},
         "category": {"type": "string"}
       },
       "required": ["value", "category"],
       "additionalProperties": false
    },

    "perValueArray": {
      "type": "array",
      "items": {"$ref": "#/definitions/perValue"}
    },

    "categoryType":{
       "oneOf": [
         {"$ref": "#/definitions/categoryValues"},
         {
           "type": "object",
           "properties": {
             "follows": {"type": "string"}
           },
           "required": ["follows"],
           "additionalProperties": false
         },
         {
           "type": "object",
           "properties": {
             "per-value": {"$ref": "#/definitions/perValueArray"}
           },
           "required": ["per-value"],
           "additionalProperties": false
         }
       ]
    },

    "mapType": {
      "type": "object",
      "properties":{
        "key": {"$ref": "#/definitions/baseType"},
        "value": {"$ref": "#/definitions/baseType"},
        "min": {"$ref": "#/definitions/integerLimit"},
        "max": {"$ref": "#/definitions/integerLimit"}
      },
      "required": ["key"],
      "additionalProperties": false
    },

    "columnType": {
      "oneOf": [
        { "$ref": "#/definitions/atomicType" },
        { "$ref": "#/definitions/mapType" },
        { "$ref": "#/definitions/valueMapType" }
      ]
    },

    "column": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/columnType"
        },
        "ephemeral": {
          "type": "boolean",
          "default": false
        },
        "mutable": {
          "type": "boolean",
          "default": true
        },
        "category": {
          "$ref": "#/definitions/categoryType"
        },
        "group": {
          "$ref": "#/definitions/groupPath"
        },
        "title": {
          "type": "string"
        },
        "doc": {
          "$ref": "#/definitions/documentation"
        },
        "relationship": {
          "$ref": "#/definitions/relationshipValues"
        },
        "emptyValue": {
          "type": ["number","string","boolean"]
        },
        "keyname": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ],
      "additionalProperties": false
    },

    "columns": {
      "type": "object",
      "patternProperties": {
        "^[_a-zA-Z][_a-zA-Z0-9]*$": {
          "$ref": "#/definitions/column"
        }
      },
      "additionalProperties": false
    },

    "groupDoc": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "$ref": "#/definitions/documentation"
        }
      },
      "additionalProperties": false
    },

    "table": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "doc": {
          "$ref": "#/definitions/documentation"
        },
        "columns": {
          "$ref": "#/definitions/columns"
        },
        "isRoot": {
          "type": "boolean",
          "default": false
        },
        "maxRows": {
          "type": "integer",
          "minimum": 1
        },
        "indexes": {
          "$ref": "#/definitions/indexArray"
        },
        "group": {
          "$ref": "#/definitions/groupPath"
        },
        "groupDoc": {
          "$ref": "#/definitions/groupDoc"
        }

      },
      "required": [
        "columns"
      ],
      "additionalProperties": false
    },

    "tableRef": {
      "type": "object",
      "properties": {
        "$ref": {
          "type": "string"
        }
      },
      "required": [
        "$ref"
      ]
    },

    "tables": {
      "type": "object",
      "patternProperties": {
         "^[_a-zA-Z][_a-zA-Z0-9]*$": {
          "$ref": "#/definitions/table"
        }
      },
      "additionalProperties": false
    }

  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "id": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "cksum": {
      "type": "string",
      "pattern": "[0-9]{12} [0-9]{7}"
    },
    "doc": {
      "$ref": "#/definitions/documentation"
    },
    "groups": {
      "$ref": "#/definitions/groups"
    },
    "tables": {
      "$ref": "#/definitions/tables"
    }
  },
  "required": [
    "name",
    "version",
    "tables"
  ],
  "additionalProperties": false
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/mirror.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/mirror.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "Mirror": {
      "columns": {
        "name": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 64
            }
          },
          "mutable": false,
          "doc": [
            "There must be a user-defined name of the mirror session."
          ]
        },
        "active": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "boolean"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "The intended state of the mirror session: active or inactive. The",
            "[operation_state](Mirror.mirror_status.operation_state) value contains the",
            "actual state in hardware (e.g. active, inactive, or error). When missing or",
            "false, the state is inactive."
          ],
          "emptyValue": false
        },
        "select_src_port": {
          "category": "configuration",
          "relationship": "reference",
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Port",
              "refType": "weak"
            },
            "min": 0,
            "max": "unlimited"
          },
          "doc": [
            "Set of Ethernet port or LAG references in [Port](Port) on which received packets",
            "are selected to be mirrored."
          ],
          "group": "/Mirroring Source(s) Configuration"
        },
        "select_dst_port": {
          "category": "configuration",
          "relationship": "reference",
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Port",
              "refType": "weak"
            },
            "min": 0,
            "max": "unlimited"
          },
          "doc": [
            "Set of Ethernet port or LAG references in [Port](Port) on which transmitted",
            "packets are selected to be mirrored."
          ],
          "group": "/Mirroring Source(s) Configuration"
        },
        "output_port": {
          "category": "configuration",
          "relationship": "reference",
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Port",
              "refType": "weak"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Ethernet port or LAG reference in [Port](Port) used to transmit the mirror",
            "packets.  There must be a valid Ethernet port or LAG for the session operation",
            "state to become active.",
            "",
            "The output port should be reserved exclusively for transmitting mirror packets",
            "for this session.  It should not pariticapte in any other network activity (e.g.",
            "Spanning Tree, LLDP etc)."
          ],
          "group": "/Mirroring Destination Configuration"
        },
        "statistics": {
          "category": "statistics",
          "type": {
            "valueType": "integer",
            "valueMap": {
              "tx_bytes": {
                "type": "integer",
                "doc": [
                  "Number of bytes transmitted through this mirror."
                ],
                "group": "/Mirror Session Statistics"
              },
              "tx_packets": {
                "type": "integer",
                "doc": [
                  "Number of packets transmitted through this mirror."
                ],
                "group": "/Mirror Session Statistics"
              }
            },
            "min": 0,
            "max": "unlimited"
          },
          "ephemeral": true,
          "group": "/Mirror Session Statistics"
        },
        "mirror_status": {
          "category": "status",
          "type": {
            "valueType": "string",
            "valueMap": {
              "operation_state": {
                "type": {
                  "type": "string",
                  "enum": [
                    "active",
                    "shutdown",
                    "internal_error",
                    "driver_error",
                    "unknown_error"
                  ]
                },
                "doc": [
                  "Operational state of the mirror session in hardware. Only the value \"active\"",
                  "means the hardware mirroring is running. Any other value, or if the key is",
                  "missing, means the session is not running."
                ],
                "group": "/Mirror Session Status",
                "emptyValue": "shutdown"
              }
            },
            "min": 0,
            "max": "unlimited"
          },
          "doc": [
            "Key-value pair(s) that report mirror status in hardware."
          ],
          "group": "/Mirror Session Status"
        },
        "other_config": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          },
          "group": "/Common Columns"
        },
        "external_ids": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          },
          "group": "/Common Columns"
        }
      },
      "indexes": [
        [
          "name"
        ]
      ],
      "title": "Mirror Sessions",
      "doc": [
        "Mirror sessions referenced from a [Bridge](Bridge).",
        "",
        "A mirror configures a bridge to send copies of selected packets to special",
        "\"mirrored\" ports, in addition to their normal destinations. Mirroring traffic",
        "may also be referred to as SPAN."
      ],
      "groupDoc": {
        "/Mirror Session Statistics": [
          "Key-value pairs that report mirror statistics.  The counts are reset to zero",
          "whenever the operation state transitions to active. The update period is",
          "controlled by [stats-update-interval](System.other_config.stats-update-interval)",
          "in table [System](System). No counts may be available initally until the first",
          "update period has elasped.  If any key-value pairs remains missing, the hardware",
          "does not support that count."
        ],
        "/Common Columns": [
          "The overall purpose of these columns is described under `Common Columns` at the",
          "beginning of this document."
        ],
        "/Mirroring Source(s) Configuration": [
          "To be selected for mirroring, a given packet must enter or leave the bridge",
          "through a selected port.  If a source port is in both the select_src_port and",
          "select_dst_port sets, then both transmitted and received packets will be",
          "mirrored."
        ]
      }
    }
  }
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/bgp_nexthop.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/bgp_nexthop.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "BGP_Nexthop": {
      "columns": {
        "ip_address": {
          "category": "status",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 45
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "IP address of the nexthop device."
          ],
          "group": "/Status"
        },
        "type": {
          "category": "status",
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "unicast"
              ]
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Type of the nexthop. Default is `unicast`."
          ],
          "group": "/Status",
          "emptyValue": "unicast"
        }
      },
      "title": "BGP Nexthops",
      "doc": [
        "List of all nexthops used by BGP. Each entry in the BGP RIB can have a reference",
        "to one or many (for ECMP) nexthop entries."
      ]
    }
  }
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/cpu_rx.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/cpu_rx.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "CPU_RX": {
      "columns": {
        "matches": {
          "category": "status",
          "type": {
            "valueType": "string",
            "valueMap": {
              "ether_type": {
                "type": {
                  "type": "integer",
                  "minInteger": 0,
                  "maxInteger": 65535
                },
                "doc": [
                  "EtherType value to match."
                ],
                "group": "/Matches Keys"
              },
              "ip_protocol": {
                "type": {
                  "type": "integer",
                  "minInteger": 0,
                  "maxInteger": 255
                },
                "doc": [
                  "IP protocol value to match."
                ],
                "group": "/Matches Keys"
              },
              "dest_multicast_mac": {
                "type": {
                  "type": "string"
                },
                "doc": [
                  "Destination multicast mac address to match."
                ],
                "group": "/Matches Keys"
              },
              "dest_multicast_ipv4": {
                "type": {
                  "type": "string"
                },
                "doc": [
                  "Destination IPv4 multicast address to match."
                ],
                "group": "/Matches Keys"
              },
              "dest_multicast_ipv6": {
                "type": {
                  "type": "string"
                },
                "doc": [
                  "Destination IPv6 multicast address to match."
                ],
                "group": "/Matches Keys"
              },
              "dest_udp_port": {
                "type": {
                  "type": "integer",
                  "minInteger": 0,
                  "maxInteger": 65535
                },
                "doc": [
                  "Destination UDP port to match."
                ],
                "group": "/Matches Keys"
              },
              "dest_ipv4": {
                "type": {
                  "type": "string"
                },
                "doc": [
                  "Destination IPv4 unicast address to match.",
                  "Used when host has several local IPv4 addresses, but only wants",
                  "traffic to be copied to CPU for one of them."
                ],
                "group": "/Matches Keys"
              },
              "dest_ipv6": {
                "type": {
                  "type": "string"
                },
                "doc": [
                  "Destination IPv6 unicast address to match.",
                  "Used when host has several local IPv6 addresses, but only wants",
                  "traffic to be copied to CPU for one of them."
                ],
                "group": "/Matches Keys"
              },
              "multicast_misses": {
                "type": {
                  "type": "string",
                  "enum": [
                    "ipv4",
                    "ipv6"
                  ]
                },
                "doc": [
                  "Multicast unknown or Multicast misses traffic.",
                  "Two rules should be created in order to enable multicast misses",
                  "traffic for ipv4 and ipv6 at same time."
                ],
                "group": "/Matches Keys"
              }
            },
            "min": 1,
            "max": "unlimited"
          },
          "mutable": false,
          "doc": [
            "Rules to match packets which are to be copied to the CPU.",
            "Something like ipv4, ipv6, mac address or protocol types.",
            "There can be one or more key-value pairs to match.",
            "If more than one match is specified packets must meet all matches",
            "to be copied to the CPU.",
            "",
            "Unique rows should be inserted using above applicable keys to",
            "match packet types and copy them to the CPU.",
            "Example: For receiving ipv4 OSPF All-Router protocol packet,",
            "OSPF daemon will create a row with:",
            "  matches column: ip_protocol:59, dest_multicast_ipv4:224.0.0.5.",
            "  port column: reference to ports on which to allow OSPF packet.",
            "  from column: process_name:\"ops-ospf\".",
            "  ops-switchd will get this update and program the ASIC and update the",
            "  status column: hw_configured: \"true\" and error: \"Ok\"",
            "",
            "And similarly OSPF will have to insert seperate rows for ipv4 OSPF DR,",
            "ipv6 All Router, and ipv6 DR.",
            "In case of invalid matching key-values or failure to program the ASIC,",
            "status column will be populated with relevent error string."
          ],
          "group": "/Configuration"
        },
        "ports": {
          "category": "status",
          "relationship": "reference",
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Port",
              "refType": "weak"
            },
            "min": 0,
            "max": "unlimited"
          },
          "doc": [
             "Specifies the set of ports in [Port](PORTS) table whose",
             "matching traffic will be copied to the CPU.",
             "Default is *NULL*, which means allow on all ports."
          ],
          "group": "/Configuration"
        },
        "vlans": {
          "category": "status",
          "relationship": "reference",
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "VLAN",
              "refType": "weak"
            },
            "min": 0,
            "max": 4094
          },
          "doc": [
            "Specifies the set of VLANs in [VLAN](VLAN) table whose",
            "matching traffic will be copied to the CPU.",
            "Default is *NULL*, which means VLAN is not considered for match."
          ],
          "group": "/Configuration"
        },
        "drop_after_copy": {
          "category": "status",
          "type": {
            "key": {
              "type": "boolean"
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Set this value to *true*, if the ASIC after copying",
            "the packet to the CPU should drop it.",
            "Default is *false*."
          ],
          "group": "/Configuration"
        },
        "from": {
          "category": "status",
          "type": {
            "key": {
              "type": "string"
            },
            "min": 1,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Name of Process/Daemon which is creating this match's row.",
            "In case when more than one process is interested in receiving same",
            "traffic class, then each of the process should create seperate rows,",
            "with their process_name's."
          ],
          "group": "/Configuration"
        },
        "hw_status": {
          "category": "status",
           "type": {
            "valueType": "string",
            "valueMap": {
              "hw_configured": {
                "type": "boolean",
                "doc": [
                  "Indicates whether the matching rule is installed in the ASIC"
                ],
                "group": "/Hardware status"
              },
              "error": {
                "type": "string",
                "doc": [
                  "Human readable error string, in case of validation error",
                  "or failure while programming the ASIC."
                ],
                "group": "/Hardware status"
              }
            },
            "min": 0,
            "max": 2
          },
          "doc": [
            "Status indicating whether the entry is successfully programmed in",
            "ASIC."
          ],
          "group": "/Hardware status"
        }
      },
      "isRoot": true,
      "title": "CPU Packet Reception",
      "doc": [
        "Traffic types which ASIC will copy to the CPU for further",
        "processing by respective daemons.",
        "This table is populated by daemons whenever they need specific",
        "traffic (ex. a protocol was enabled on a VLAN or port)."
      ],
      "groupDoc": {
        "/Matches Keys": [
          "These values define the possible filters or reasons to",
          "copy a packet to the CPU"
        ],
        "/Hardware status": [
          "Display the hardware configuration results, used to show",
          "if configuration was success or not and what was the error"
        ]
      }
    }
  }
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/ssl.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/ssl.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "SSL": {
      "columns": {
        "private_key": {
          "category": "configuration",
          "type": "string",
          "doc": [
            "Name of a PEM file containing the private key used as the switch's identity for",
            "SSL connections to the controller."
          ]
        },
        "certificate": {
          "category": "configuration",
          "type": "string",
          "doc": [
            "Name of a PEM file containing a certificate, signed by the certificate authority",
            "(CA) used by the controller and manager, that certifies the switch's private",
            "key, identifying a trustworthy switch."
          ]
        },
        "ca_cert": {
          "category": "configuration",
          "type": "string",
          "doc": [
            "Name of a PEM file containing the CA certificate used to verify that the switch",
            "is connected to a trustworthy controller."
          ]
        },
        "bootstrap_ca_cert": {
          "category": "configuration",
          "type": "boolean",
          "doc": [
            "If set to `true`, then OpenSwitch will attempt to obtain the CA certificate from",
            "the controller on its first SSL connection and save it to the named PEM file. If",
            "it is successful, it will immediately drop the connection and reconnect, and",
            "from then on all SSL connections must be authenticated by a certificate signed",
            "by the CA certificate thus obtained.  _This option exposes the SSL connection to",
            "a man-in-the-middle attack obtaining the initial CA certificate._  It may still",
            "be useful for bootstrapping."
          ]
        },
        "external_ids": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          },
          "group": "/Common Columns"
        }
      },
      "maxRows": 1,
      "doc": [
        "SSL configuration for an System."
      ],
      "groupDoc": {
        "/Common Columns": [
          "The overall purpose of these columns is described under `Common Columns` at the",
          "beginning of this document."
        ]
      }
    }
  }
}
