=== jxtxinbing/opssrc_org/ops/schema/ops.metaschema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://git.openswich.net/schema/ops-db-metaschema#",
  "description": "OpenSwitch Database metaschema",
  "definitions": {

    "atomicDataType": {
      "type": "string",
      "enum": [
        "integer",
        "real",
        "boolean",
        "string",
        "uuid"
      ]
    },

    "categoryValues": {
      "type": "string",
      "enum": [
        "configuration",
        "status",
        "statistics"
      ]
    },

    "relationshipValues": {
      "type": "string",
      "enum": [
        "reference",
        "1:m",
        "m:1"
      ]
    },

    "refTypeValues": {
      "type": "string",
      "enum": [
        "strong",
        "weak",
        "weak_gc"
      ]
    },

    "documentation": {
      "type": "array",
      "items": {
          "type": "string"
      },
      "uniqueItems": false
    },

    "atomicType": {
      "oneOf": [
        {
          "$ref": "#/definitions/atomicDataType"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "$ref": "#/definitions/atomicDataType"
            }
          },
          "required": [
            "type"
          ],
          "additionalProperties": false
        }
      ]
    },

    "integerType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^integer$"},
        "enum": {
          "type": "array",
          "items": {"type": "integer"},
          "minItems": 1,
          "uniqueItems": true
        },
        "minInteger": {"type": "integer"},
        "maxInteger": {"type": "integer"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "realType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^real$"},
        "enum": {
          "type": "array",
          "items": {"type": "number"},
          "minItems": 1,
          "uniqueItems": true
        },
        "minReal": {"type": "number"},
        "maxReal": {"type": "number"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "stringType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^string$"},
        "enum": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"},
        "minLength": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"},
        "maxLength": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "uuidType": {
      "type": "object",
      "properties": {
        "type": {"type": "string", "pattern": "^uuid$"},
        "enum": {"$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"},
        "refTable": {"type": "string", "pattern": "^[_a-zA-Z][_a-zA-Z0-9]*$"},
        "refType": {"$ref": "#/definitions/refTypeValues"}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "baseType":{
      "anyOf": [
        {"$ref":"#/definitions/atomicType"},
        {"$ref":"#/definitions/integerType"},
        {"$ref":"#/definitions/realType"},
        {"$ref":"#/definitions/stringType"},
        {"$ref":"#/definitions/uuidType"}
      ]
    },

    "valueMap": {
      "type": "object",
      "properties": {
        "type": {"$ref": "#/definitions/baseType"},
        "doc": {"$ref": "#/definitions/documentation"},
        "group": {"$ref": "#/definitions/groupPath"},
        "emptyValue": {"type": ["number","string","boolean"]}
      },
      "required": ["type"],
      "additionalProperties": false
    },

    "valueMapField": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "$ref": "#/definitions/valueMap"
        }
      },
      "additionalProperties": false
    },

    "valueMapType":{
      "type": "object",
      "properties":{
        "omitCodeGeneration": {"type":"boolean","default": false},
        "valueType": {"$ref": "#/definitions/baseType"},
        "valueMap": {"$ref": "#/definitions/valueMapField"},
        "min": {"$ref": "#/definitions/integerLimit"},
        "max": {"$ref": "#/definitions/integerLimit"}
      },
      "required": ["valueMap","valueType"],
      "additionalProperties": false
    },

    "integerLimit": {
      "anyOf": [
        {"$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"},
        {"type": "string", "pattern": "^unlimited$"}
      ]
    },

    "path": {
      "type": "string"
    },

    "pathArray": {
      "type": "array",
      "items": {"$ref": "#/definitions/path"}
    },

    "indexArray": {
      "type": "array",
      "items": {
        "$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"
      }
    },

    "groupPath": {
      "anyOf": [
        {"$ref": "#/definitions/path"},
        {"$ref": "#/definitions/pathArray"}
      ]
    },

    "perValue": {
       "type": "object",
       "properties":{
         "value": {},
         "category": {"type": "string"}
       },
       "required": ["value", "category"],
       "additionalProperties": false
    },

    "perValueArray": {
      "type": "array",
      "items": {"$ref": "#/definitions/perValue"}
    },

    "categoryType":{
       "oneOf": [
         {"$ref": "#/definitions/categoryValues"},
         {
           "type": "object",
           "properties": {
             "follows": {"type": "string"}
           },
           "required": ["follows"],
           "additionalProperties": false
         },
         {
           "type": "object",
           "properties": {
             "per-value": {"$ref": "#/definitions/perValueArray"}
           },
           "required": ["per-value"],
           "additionalProperties": false
         }
       ]
    },

    "mapType": {
      "type": "object",
      "properties":{
        "key": {"$ref": "#/definitions/baseType"},
        "value": {"$ref": "#/definitions/baseType"},
        "min": {"$ref": "#/definitions/integerLimit"},
        "max": {"$ref": "#/definitions/integerLimit"}
      },
      "required": ["key"],
      "additionalProperties": false
    },

    "columnType": {
      "oneOf": [
        { "$ref": "#/definitions/atomicType" },
        { "$ref": "#/definitions/mapType" },
        { "$ref": "#/definitions/valueMapType" }
      ]
    },

    "column": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/columnType"
        },
        "ephemeral": {
          "type": "boolean",
          "default": false
        },
        "mutable": {
          "type": "boolean",
          "default": true
        },
        "category": {
          "$ref": "#/definitions/categoryType"
        },
        "group": {
          "$ref": "#/definitions/groupPath"
        },
        "title": {
          "type": "string"
        },
        "doc": {
          "$ref": "#/definitions/documentation"
        },
        "relationship": {
          "$ref": "#/definitions/relationshipValues"
        },
        "emptyValue": {
          "type": ["number","string","boolean"]
        },
        "keyname": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ],
      "additionalProperties": false
    },

    "columns": {
      "type": "object",
      "patternProperties": {
        "^[_a-zA-Z][_a-zA-Z0-9]*$": {
          "$ref": "#/definitions/column"
        }
      },
      "additionalProperties": false
    },

    "groupDoc": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "$ref": "#/definitions/documentation"
        }
      },
      "additionalProperties": false
    },

    "table": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "doc": {
          "$ref": "#/definitions/documentation"
        },
        "columns": {
          "$ref": "#/definitions/columns"
        },
        "isRoot": {
          "type": "boolean",
          "default": false
        },
        "maxRows": {
          "type": "integer",
          "minimum": 1
        },
        "indexes": {
          "$ref": "#/definitions/indexArray"
        },
        "group": {
          "$ref": "#/definitions/groupPath"
        },
        "groupDoc": {
          "$ref": "#/definitions/groupDoc"
        }

      },
      "required": [
        "columns"
      ],
      "additionalProperties": false
    },

    "tableRef": {
      "type": "object",
      "properties": {
        "$ref": {
          "type": "string"
        }
      },
      "required": [
        "$ref"
      ]
    },

    "tables": {
      "type": "object",
      "patternProperties": {
         "^[_a-zA-Z][_a-zA-Z0-9]*$": {
          "$ref": "#/definitions/table"
        }
      },
      "additionalProperties": false
    }

  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "id": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "cksum": {
      "type": "string",
      "pattern": "[0-9]{12} [0-9]{7}"
    },
    "doc": {
      "$ref": "#/definitions/documentation"
    },
    "groups": {
      "$ref": "#/definitions/groups"
    },
    "tables": {
      "$ref": "#/definitions/tables"
    }
  },
  "required": [
    "name",
    "version",
    "tables"
  ],
  "additionalProperties": false
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/mclag_remote_interface.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/mclag_remote_interface.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "MCLAG_Remote_Interface": {
      "columns": {
        "name": {
          "category": "status",
          "type": "string",
          "mutable": false,
          "doc": [
            "Name of the peer interface."
          ],
          "group": "/partner information"
        },
        "lacp_partner_system_id": {
          "category": "status",
          "type": {
            "key": {
              "type": "string"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Peer interface's LACP partner system ID."
          ],
          "group": "/partner information"
        },
        "lacp_partner_port_id": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Peer interface's LACP partner port ID."
          ],
          "group": "/partner information"
        },
        "lacp_partner_key": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Peer interface's LACP partner key."
          ],
          "group": "/partner information"
        },
        "lacp_partner_state": {
          "category": "status",
          "type": {
            "key": {
              "type": "string"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "LACP partner state."
          ],
          "group": "/partner link status"
        },
        "lacp_actor_system_id": {
          "category": "status",
          "type": {
            "key": {
              "type": "string"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Peer interface's LACP actor system ID."
          ],
          "group": "/actor information"
        },
        "lacp_actor_port_id": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Peer interface's LACP actor port ID."
          ],
          "group": "/actor information"
        },
        "lacp_actor_key": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Peer interface's LACP actor key."
          ],
          "group": "/actor information"
        },
        "lacp_actor_state": {
          "category": "status",
          "type": {
            "key": {
              "type": "string"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Peer interface's LACP actor state."
          ],
          "group": "/actor information"
        },
        "lacp_port_priority": {
          "category": "status",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1,
              "maxInteger": 65535
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "LACP port-priority."
          ]
        },
        "admin_state": {
          "category": "status",
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "up",
                "down"
              ]
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "The administrative state of the physical network link."
          ],
          "group": "/partner link status"
        },
        "link_state": {
          "category": "status",
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "up",
                "down"
              ]
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "The observed state of the physical network link. This is ordinarily the link's",
            "carrier status."
          ],
          "group": "/partner link status"
        },
        "link_speed": {
          "category": "status",
          "type": {
            "key": "integer",
            "min": 0,
            "max": 1
          },
          "doc": [
            "The negotiated speed of the physical network link in bits per second. Valid",
            "values are positive integers greater than 0."
          ],
          "group": "/partner link status"
        },
        "duplex": {
          "category": "status",
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "half",
                "full"
              ]
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "The duplex mode of the physical network link."
          ],
          "group": "/partner link status"
        }
      },
      "indexes": [
        [
          "name"
        ]
      ],
      "isRoot": true,
      "title": "Remote MCLAG information",
      "doc": [
        "Each entry contains the information about a physical interface on the peer",
        "switch which is configured for MCLAG. This information is determined by",
        "exchanging packets over the ISL link between the MLAG switches."
      ]
    }
  }
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/nexthop.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/nexthop.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "Nexthop": {
      "columns": {
        "ip_address": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 45
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "IP address of the nexthop device."
          ],
          "group": "/Configuration"
        },
        "ports": {
          "category": "configuration",
          "relationship": "reference",
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Port",
              "refType": "weak"
            },
            "min": 0,
            "max": "unlimited"
          },
          "doc": [
            "List of outgoing ports. Nexthop entries of type `unicast` can have atmost 1",
            "port."
          ],
          "group": "/Configuration"
        },
        "type": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "unicast"
              ]
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Type of the nexthop. Default is `unicast`."
          ],
          "group": "/Configuration",
          "emptyValue": "unicast"
        },
        "selected": {
          "category": "status",
          "type": {
            "key": {
              "type": "boolean"
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Indicates if this nexthop is actively participating in forwarding. Multiple",
            "nexthops can exist for each route entry but the routing protocol can indicate if",
            "a particular nexthop should not be used in forwarding. Default is `true`."
          ],
          "group": "/Configuration",
          "emptyValue": true
        },
        "weight": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 4294967295
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Weight is used to differentially balance the packets. Example: For a route if",
            "there are 2 nexthops nh1 with weight 5 and nh2 with weight 1, then for every 5",
            "packets that uses nh1, one packet will use nh2. In the first release, the above",
            "case is not supported. Only ECMP is supported. Default is 0 (for static routes)."
          ],
          "group": "/Configuration",
          "emptyValue": 0
        },
        "status": {
          "category": "status",
          "type": {
            "valueType": "string",
            "valueMap": {
              "arp_resolved": {
                "type": "boolean",
                "doc": [
                  "Indicate if ARP is resolved for this entry. If the ARP entry is missing, this",
                  "value is `false`"
                ],
                "group": "/Status",
                "emptyValue": "false"
              },
              "error": {
                "type": "string",
                "doc": [
                  "Human readable error string."
                ],
                "group": "/Status"
              },
              "hw_configured": {
                "type": "boolean",
                "doc": [
                  "Indicate if nexthop programmed in the asic. If the ARP entry is missing, this",
                  "value is `false`"
                ],
                "group": "/Status",
                "emptyValue": "false"
              }
            },
            "min": 0,
            "max": "unlimited"
          },
          "ephemeral": true,
          "group": "/Status"
        },
        "other_config": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          },
          "group": "/Common Columns"
        },
        "external_ids": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          },
          "group": "/Common Columns"
        }
      },
      "title": "Nexthops",
      "doc": [
        "Global list of all the nexthops as used by the [Route](Route) table. Each entry",
        "in the [Route](Route) can have a reference to one or many(for ECMP) entries in",
        "this table."
      ],
      "groupDoc": {
        "/Status": [
          "Status information to indicate the current state of the nexthop."
        ],
        "/Common Columns": [
          "The overall purpose of these columns is described under `Common Columns` at the",
          "beginning of this document."
        ]
      }
    }
  }
}

=== jxtxinbing/opssrc_org/ops/schema/openswitch/common/acl_entry.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common/acl_entry.json#",
  "name": "OpenSwitch",
  "version": "0.1.8",
  "tables": {
    "ACL_Entry": {
      "columns": {
        "comment": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 256
            },
            "min": 0,
            "max": 1
          },
          "doc": [
            "Comment to associate with the specified ACE. Optional parameter."
          ]
        },
        "action": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "permit",
                "deny"
              ]
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Match Action: Optional parameter for IPv4 ACL entries. There are two types:",
            "\"permit\" and \"deny\" If no action is specified the ACE will not be programmed in",
            "hw."
          ]
        },
        "src_ip": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 100
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Source IPv4 Address: Optional parameter.  If no IP address is specified the ACE",
            "will not match on source IP address.  The following IPv4 address formats are",
            "accepted: X.X.X.X/X.X.X.X"
          ]
        },
        "dst_ip": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "string",
              "maxLength": 100
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Destination IPv4 Address: Optional parameter.  If no IP address is specified the",
            "ACE will not match on destination IP address  The following IPv4 address formats",
            "are accepted: X.X.X.X/X.X.X.X"
          ]
        },
        "protocol": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 255
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "IPv4 Protocol Optional parameter.  If no protocol is specified the ACE will not",
            "match on protocol."
          ]
        },
        "src_l4_port_min": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 65535
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Source L4 Port: specifies the IPv4 L4 source port to be used as the minimum",
            "value.  It is used in conjunction with src_l4_port_max and",
            "src_l4_port_range_reverse to determine the desired source L4 port functionality.",
            "Optional parameter for IPv4 ACL entries."
          ],
          "group": "/ACL L4 Port Configuration"
        },
        "src_l4_port_max": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 65535
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Source L4 Port Max: specifies the maximum value It is used in conjunction with",
            "src_l4_port_min and src_l4_port_range_reverse to determine the desired source L4",
            "port functionality.  Optional parameter for IPv4 ACL entries."
          ],
          "group": "/ACL L4 Port Configuration"
        },
        "src_l4_port_range_reverse": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "boolean"
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Specifies if the values in src_l4_port_min and src_l4_port_max should be treated",
            "as specifying values not to be matched. Optional parameter for IPv4 ACL entries.",
            "Applicable to TCP and UDP protocols."
          ],
          "group": "/ACL L4 Port Configuration"
        },
        "dst_l4_port_min": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 65535
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Source L4 Port: specifies the IPv4 L4 source port to be used as the minimum",
            "value.  It is used in conjunction with dst_l4_port_max and",
            "dst_l4_port_range_reverse to determine the desired destination L4 port",
            "functionality.  Optional parameter for IPv4 ACL entries."
          ],
          "group": "/ACL L4 Port Configuration"
        },
        "dst_l4_port_max": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 65535
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Destination L4 Port Max: specifies the maximum value It is used in conjunction",
            "with dst_l4_port_min and dst_l4_port_range_reverse to determine the desired",
            "destination L4 port functionality.  Optional parameter for IPv4 ACL entries."
          ],
          "group": "/ACL L4 Port Configuration"
        },
        "dst_l4_port_range_reverse": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "boolean"
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Specifies if the values in dst_l4_port_min and dst_l4_port_max should be treated",
            "as specifying values not to be matched. Optional parameter for IPv4 ACL entries.",
            "Applicable to TCP and UDP protocols."
          ],
          "group": "/ACL L4 Port Configuration"
        },
        "log": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "boolean"
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Log Action: enable ACL logging for packets that match this ACL entry Optional",
            "parameter for IPv4 ACL entries The following value is accepted: true"
          ]
        },
        "count": {
          "category": "configuration",
          "type": {
            "key": {
              "type": "boolean"
            },
            "min": 0,
            "max": 1
          },
          "mutable": false,
          "doc": [
            "Count Action: enable hit counts in hardware for packets that match this ACL",
            "entry Optional parameter for IPv4 ACL entries The following value is accepted:",
            "true"
          ]
        },
        "other_config": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          }
        },
        "external_ids": {
          "category": "configuration",
          "type": {
            "key": "string",
            "value": "string",
            "min": 0,
            "max": "unlimited"
          }
        }
      },
      "title": "Access Control Entry",
      "groupDoc": {
        "/ACL L4 Port Configuration": [
          "L4 Port: specifies the IPv4 L4 port to be used as the minimum value.  It is used",
          "in conjunction with src/dst_l4_port_max and src/dst_l4_port_range_reverse to",
          "determine the desired L4 port functionality:  Applicable to TCP and UDP",
          "protocols."
        ]
      }
    }
  }
}
